### ISSUE TITLE
Can't Auth to Rackspace

### ISSUE THREAD

**Issue by code-ape** [mitchellh/packer#1755]
I've been trying with no success to use Packer to build an image with Rackspace. Currently here is my config:

```yaml
{
  "variables": {
    "rackspace_username": "",
    "rackspace_password": ""
  },
  "builders": [
    {
      "type": "openstack",
      "username": "{{user `rackspace_username`}}",
      "password": "{{user `rackspace_password`}}",
      "provider": "rackspace-us",
      "region": "IAD",
      "ssh_username": "root",
      "image_name": "Test image {{timestamp}}",
      "source_image": "ea98e34c-7a25-4670-9e2a-7fa9815f6c9f",
      "flavor": "2"
    }
  ],
  "provisioners": [
    {
      "type": "shell",
      "inline": [
        "sleep 30",
        "sudo apt-get update",
        "sudo apt-get upgrade -y"
      ]
    }
  ]
}
```
But when I run:
```
packer build -var "rackspace_username=foo" -var "rackspace_password=bar" test.json 
```
I get:
```
openstack output will be in this color.

Build 'openstack' errored: Auth failed. Bad credentials.

==> Some builds didn't complete successfully and had errors:
--> openstack: Auth failed. Bad credentials.

==> Builds finished but no artifacts were created.
```

Any ideas?
