### ISSUE TITLE
packer build docker image error.

### ISSUE THREAD

**Issue by polarlights** [mitchellh/packer#3053]
## Description of problem:

I build docker images by packer. First, I run it with shell version, ie. builder type is `null`. And then, I run it with builder type `docker`.

With builder type `null`, it works well and without any errors. However, when I build it with docker, and install mysql, it says: "msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials"。The code is below:

``` yaml

- name: make sure mysql is started
  service:
    name: mysql
    enabled: yes
    state: started
  sudo: true

- name: MySQL | Test whether the root password has already been changed (external hostname).
  mysql_user:
    user: root
    host: "{{item}}"
    password: "{{mysql_root_password}}"
    login_user: root
    login_password: "{{mysql_root_password}}"
    priv: "*.*:ALL,GRANT"
  with_items:
   - "{{ansible_hostname}}"
   - 127.0.0.1
   - ::1
   - localhost
  register: root_pw_already_set
  ignore_errors: yes
  when: ansible_hostname != 'localhost'


- name: MySQL | Changing the root password (external hostname).
  mysql_user:
    user: root
    host: "{{item}}"
    password: "{{mysql_root_password}}"
    login_user: root
    login_password: "{{mysql_default_root_password}}"
    priv: "*.*:ALL,GRANT"
  with_items:
   - "{{ansible_hostname}}"
   - 127.0.0.1
   - ::1
   - localhost
  when: "root_pw_already_set|failed and ansible_hostname != 'localhost'"

```
## packer version:

0.8.6
## `docker version`:

> Client:
>  Version:      1.9.1
>  API version:  1.21
>  Go version:   go1.4.2
>  Git commit:   a34a1d5
>  Built:        Fri Nov 20 13:12:04 UTC 2015
>  OS/Arch:      linux/amd64
> 
> Server:
>  Version:      1.9.1
>  API version:  1.21
>  Go version:   go1.4.2
>  Git commit:   a34a1d5
>  Built:        Fri Nov 20 13:12:04 UTC 2015
>  OS/Arch:      linux/amd64
## `docker info`:

> Containers: 19
> Images: 7
> Server Version: 1.9.1
> Storage Driver: aufs
>  Root Dir: /var/lib/docker/aufs
>  Backing Filesystem: extfs
>  Dirs: 45
>  Dirperm1 Supported: false
> Execution Driver: native-0.2
> Logging Driver: json-file
> Kernel Version: 3.13.0-48-generic
> Operating System: Ubuntu 14.04.2 LTS
> CPUs: 1
> Total Memory: 992.5 MiB
## `uname -a`:

Linux ip-172-31-17-29 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
## Environment details (AWS, VirtualBox, physical, etc.):

AWS by SSH
## How reproducible:

part of the code can be found [here](https://github.com/polarlights/ansible_packer_example/blob/master/templates/production/mysql.json), and the code, I didn't change the builder to `docker`.

just run `packer build  templates/production/docker_mysql.json`
## Actual Results:

The whole log can be found [here](https://gist.github.com/polarlights/7d828a33fbab4c7d000e)

>  docker: TASK: [mysql | MySQL | Test whether the root password has already been changed (external hostname).] ***
>     docker: failed: [127.0.0.1] => (item=0679b2f24b7c) => {"failed": true, "item": "0679b2f24b7c"}
>     docker: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
>     docker: ...ignoring
>     docker: failed: [127.0.0.1] => (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1"}
>     docker: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
>     docker: ...ignoring
>     docker: failed: [127.0.0.1] => (item=::1) => {"failed": true, "item": "::1"}
>     docker: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
>     docker: ...ignoring
>     docker: failed: [127.0.0.1] => (item=localhost) => {"failed": true, "item": "localhost"}
>     docker: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
>     docker: ...ignoring
>     docker:
>     docker: TASK: [mysql | MySQL | Changing the root password (external hostname).] *******
>     docker: failed: [127.0.0.1] => (item=0679b2f24b7c) => {"failed": true, "item": "0679b2f24b7c"}
>     docker: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
>     docker: failed: [127.0.0.1] => (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1"}
>     docker: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
>     docker: failed: [127.0.0.1] => (item=::1) => {"failed": true, "item": "::1"}
>     docker: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
>     docker: failed: [127.0.0.1] => (item=localhost) => {"failed": true, "item": "localhost"}
>     docker: msg: unable to connect to database, check login_user and login_password are correct or ~/.my.cnf has the credentials
## Expected Results:

build without any error.
## Additional info:

none
