### ISSUE TITLE
Chef validation_key_path not being propagated to target

### ISSUE THREAD

**Issue by don-code** [mitchellh/packer#3263]
The `validation_key_path` parameter does not appear to have the expected effect after upgrading from Packer 0.8.6 to Packer 0.9.0. This was tested as working in Packer 0.8.6 and not working in Packer 0.9.0 on CentOS 6.7 and OS X  10.9.

A chef-client provisioner which will exhibit this is:
```
{
   "server_url": "https://some.chef.server",
   "type": "chef-client",
   "validation_client_name": "validator-name",
   "validation_key_path": "/path/to/validator.pem",
 }
```
The /tmp/packer-chef-client/client.rb which is generated on the target machine lacks the `validation_key` parameter, but does have the `validation_client_name` parameter filled out. Additionally, the validation key does get set up at `/tmp/packer-chef-client/validation.pem`. Chef as a result defaults to assuming the validation key is at `/etc/chef/validation.pem` and fails.

**Comment by jlspies1** [comment]
+1 on this. Looking at the code, the latest change [https://github.com/mitchellh/packer/commit/87532b1b0076a0bd8613e49e5b8ec4f5952750b0] seems to have introduced this issue. From what I can see, the **remoteValidationKeyPath** variable is initialized to "" (empty string) on line 211 of the latest file. From what I can see, the **remoteValidationKeyPath** is then used on line 238 to create the Chef configuration file. Unfortunately, the **remoteValidationKeyPath** has never been updated and will ALWAYS be an empty string. 

It looks like this code snippet:
```if p.config.ValidationKeyPath != "" {
		remoteValidationKeyPath = fmt.Sprintf("%s/validation.pem", p.config.StagingDir)
		if err := p.uploadFile(ui, comm, remoteValidationKeyPath, p.config.ValidationKeyPath); err != nil {
			return fmt.Errorf("Error copying validation key: %s", err)
		}
	}
```
Originally came before (around line 183 of the previous version of the code) the Chef config template was created, and that code snippet was responsible for actually setting the **remoteValidationKeyPath**. In the latest code update, however, the above snippet was moved to about line 253 and, more importantly, it not comes after the call to `p.createConfig(...)`.

I'm not sure if that resequencing was intentional. If not, the fix should be as easy as changing the sequence again.

**Comment by scalp42** [comment]
Can confirm, not working anymore in `0.9.0` (from `0.8.6`).

**Comment by Chili-Man** [comment]
I'm also running into this issue in packer 0.10.0

**Comment by b-dean** [comment]
PR #3224 fixes this. I'm not sure why they don't just merge it. I've been using a packer with that PR merged and the chef-client provisioner has been working great. If you have go installed you can just do this:

```bash
go get github.com/mitchellh/packer
cd $GOPATH/src/github.com/mitchellh/packer
git remote add -f -t fix_remove_validation_key_path versionone git@github.com:versionone/packer.git
git merge versionone/fix_remove_validation_key_path -m "merge PR 3224"
make
```

**Comment by scalp42** [comment]
@b-dean thanks for the heads up and instructions :+1:

**Comment by swade1987** [comment]
same issue with windows 2012 r2 instance 

```
amazon-ebs: Uploading packer/scripts/windows/parliamentary-digital-service-validator.pem...
    amazon-ebs: Creating JSON attribute file
    amazon-ebs: Executing Chef: c:/opscode/chef/bin/chef-client.bat --no-color -c C:/Windows/Temp/packer-chef-client/client.rb -j C:/Windows/Temp/packer-chef-client/first-boot.json
    amazon-ebs: [2016-03-18T23:46:19+00:00] INFO: *** Chef 12.8.1 ***
    amazon-ebs: [2016-03-18T23:46:19+00:00] INFO: Chef-client pid: 2772
    amazon-ebs: [2016-03-18T23:47:03+00:00] INFO: Client key C:/Windows/Temp/packer-chef-client/client.pem is not present - registering
    amazon-ebs: [2016-03-18T23:47:03+00:00] WARN: Failed to read the private key C:\chef\validation.pem: #<Errno::ENOENT: No such file or directory - C:\chef\validation.pem>
    amazon-ebs:
    amazon-ebs: ================================================================================
    amazon-ebs: Chef encountered an error attempting to create the client "packer-56ec92cc-e19b-4ae3-2e67-514e0763b173"
    amazon-ebs: ================================================================================
    amazon-ebs:
    amazon-ebs: Private Key Not Found:
    amazon-ebs: ----------------------
    amazon-ebs: Your private key could not be loaded. If the key file exists, ensure that it is
    amazon-ebs: readable by chef-client.
    amazon-ebs:
    amazon-ebs: Relevant Config Settings:
    amazon-ebs: -------------------------
    amazon-ebs: validation_key "C:\chef\validation.pem"
    amazon-ebs:
    amazon-ebs: [2016-03-18T23:47:03+00:00] ERROR: Running exception handlers
    amazon-ebs: [2016-03-18T23:47:03+00:00] ERROR: Exception handlers complete
    amazon-ebs: [2016-03-18T23:47:03+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
    amazon-ebs: [2016-03-18T23:47:03+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    amazon-ebs: [2016-03-18T23:47:03+00:00] FATAL: Chef::Exceptions::PrivateKeyMissing: I cannot read C:\chef\validation.pem, which you told me to use to sign requests!
```
