### ISSUE TITLE
Install dependencies for ansible-local with a ansible-galaxy file

### ISSUE THREAD

**Issue by JoakimLofgren** [mitchellh/packer#3301]
It would be nice if you could just say:

```yml
{
  "type": "ansible-local",
  "playbook_file": "local.yml",
  "galaxy": "requirements.yml"
}
```

And then it would install the specified roles in that file.

Currently I am trying to make this work by doing:

```yml
{
  "type": "ansible-local",
  "command": "ansible-galaxy install -v -r requirements.yml -p roles/ && ansible-playbook",
  "playbook_file": "local.yml"
}
```

Like @rvangundy mentioned in #1000

**Comment by JoakimLofgren** [comment]
My current workaround is to before ansible-local actually download the roles locally:

```yml
{
      "type": "shell-local",
      "command": "ansible-galaxy install -v -r requirements.yml -p roles/"
}
```

But that also requires ansible to be installed on the machine running packer.
