### ISSUE TITLE
Ansible remote provisioning always connect to localhost

### ISSUE THREAD

**Issue by vankhoa011** [mitchellh/packer#3564]
I used Packer to create AMI ( amazon-ebs  ) and Ansible remote for provisioning.
However, Packer always connect to localhost .

The log file: 
https://gist.github.com/vankhoa011/a6800c130b8fecdb3de12bcf48a50036

Packer version: 0.10.1
Packer template:
```
{
  "builders": [{
    "type": "amazon-ebs",
    "region": "us-east-1",
    "source_ami": "ami-a1fa1acc",
    "instance_type": "t2.micro",
    "ssh_username": "ec2-user",
    "ami_name": "ecs {{timestamp}}",
    "vpc_id": "vpc-0a38056f",
    "subnet_id": "subnet-b829a293",
    "associate_public_ip_address": "true"
  }],
  "provisioners": [{
    "type": "ansible",
    "playbook_file": "./playbook.yml",
    "extra_arguments": "-vvvv",
    "user": "ec2-user",
    "host_alias": "default",
    "ansible_env_vars": ["ANSIBLE_HOST_KEY_CHECKING=False", "ANSIBLE_SSH_ARGS='-o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s'", "ANSIBLE_NOCOLOR=True"]
  }]
}
```
playbook.yml

```
- hosts: default
  gather_facts: True
  user: ec2-user
  sudo: True
  roles:
    - logstash-forwarder
    - logrotate
    - newrelic
```
