### ISSUE TITLE
Improve output of packer AMIs that were built

### ISSUE THREAD

**Issue by gtmtech** [mitchellh/packer#4084]
Packer 0.10.2

When building AMIs, this is the (un)helpful output at the end:

```
==> Builds finished. The artifacts of successful builds are:
--> myimage1: AMIs were created:

eu-west-1: ami-82b2xxxx
--> myimage2: AMIs were created:

eu-west-1: ami-09b0xxxx
```

Except, its really not that useful - a really ugly multi-line format, making it needlessly difficult to process (Suppose after packering I want a script to pick up the built AMIs and do something, like... inject to terraform or whatever).

Why not something like this instead:

```
myimage1:
  region: eu-west-1
  amiid: ami-82b2xxxx
myimage2:
  region: eu-west-1
  amiid: ami-09b0xxxx
```

In this case I can pop the output straight into a yaml parser and off I go, rather than have to come up with some multi-line parsing regexing tool myself. 

Or a CSV or a JSON or ..... virtually anything would be better than current.

Thanks!
