### ISSUE TITLE
packer ansible sudo issue

### ISSUE THREAD

**Issue by Firxiao** [mitchellh/packer#4263]
- Packer version from `packer version`
Packer v0.12.0
ansible 2.2.0.0

- Host platform
Red Hat Enterprise Linux Server release 6.7
- Debug log output from `PACKER_LOG=1 packer build template.json`.
[log](https://gist.github.com/Firxiao/4a94e2aeb6434fa397644175b3c74c79)
- The _simplest example template and scripts_ needed to reproduce the bug.
```
"provisioners": [{
       "type": "ansible",
       "playbook_file": "./playbook.yml",
       "ansible_env_vars": [ "ANSIBLE_HOST_KEY_CHECKING=False", "ANSIBLE_SSH_ARGS='-o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s'", "ANSIBLE_NOCOLOR=True","become=true","become_method=sudo" ]
  }]
```
playbook.yml
```
- hosts: all
  gather_facts: true
  become: yes
  become_method: sudo
  remote_user: ec2-user
  roles:
  - base
```
- issue:
I have tested playbook only , it run right , but via packer it  can't run correctly, say need root to run some sommand. 
And I have try add _sudo: yes_ or _become:true become_method: sudo_, but it doesn't work.
anyone can help? Thanks a lot.
