### ISSUE TITLE
ami_block_device_mappings not attaching multiple EBS with packer

### ISSUE THREAD

**Issue by mrityunjay308** [mitchellh/packer#4344]
I am using packer to create Amazon backed EBS AMI adding 2 block devices, 1 root and another ebs attached to it. The block device mapping is not attaching the ebs block to the ami or temporary instance created. My code block looks like (only details with block device mapping added):
```
 "ami_block_device_mappings":[{
        "device_name":"/dev/xvda",
        "volume_size":8,
        "volume_type":"gp2",
        "encrypted":false,
        "delete_on_termination":true
       },
       {
        "device_name":"/dev/sdb",
        "volume_size":50,
        "volume_type":"gp2",
        "encrypted":true,
        "delete_on_termination":true
       }]
```

And the provisioner code goes as:
```
"provisioners": [
    {
        "type" : "shell",
        "inline" : [
            "sleep 30",
            "sudo yum update -y",
            "sudo yum-config-manager --enable epel",
            "sudo yum install ansible -y",
            "sleep 30",
            "sudo fdisk -l"
        ]
    } ]
```

fdisk -l shows that only 1 block added

```
    amazon-ebs: Disk /dev/xvda: 8589 MB, 8589934592 bytes, 16777216 sectors
    amazon-ebs: Units = sectors of 1 * 512 = 512 bytes
    amazon-ebs: Sector size (logical/physical): 512 bytes / 512 bytes
    amazon-ebs: I/O size (minimum/optimal): 512 bytes / 512 bytes
    amazon-ebs: Disk label type: gpt
    amazon-ebs:
    amazon-ebs:
    amazon-ebs: #         Start          End    Size  Type            Name
    amazon-ebs: 1         4096     16777182      8G  Linux filesyste Linux
    amazon-ebs: 128         2048         4095      1M  BIOS boot parti BIOS Boot Partition
```

The version I am using is packer_0.12.1_windows_amd64.

Thanks and Regards,
Jay
