### ISSUE TITLE
Ansible (remote) inventory file append to existing inventory file

### ISSUE THREAD

**Issue by anandkumarpatel** [mitchellh/packer#4505]
I have been trying to get packer and our ansible scripts to play nicely together however, I have ran into an issue.

Ansible creates its own inventory file. This means we can not supply our own inventory file (via `--extra_args =-i ./hosts-file`) AND have access to the build machine. We need this use case because we define hostname with native ansible varibles gotten from facts meaning we need to have redis in our inventory as well. Is there a way to use an existing inventory file AND have the new host added to inventory?

Toy Example:
ansible-playbook file

```
- hosts: redis

 - hosts: parkerHost
   tasks:
   - set_fact:
       redis_host: "{{ hostvars[groups['redis'][0]]['ansible_default_ipv4']['address'] }}"
   - shell: "echo {{ redis_host }}"
```
packer code
```
{
    "type": "ansible",
    "playbook_file": play.yml",
    "groups": ["packerHost"],
    "extra_arguments":  [ "--extra-vars", "-i ./hosts"],
  }
```

With the above, `redis_host` variable is defined but `packerHost` does not exist. If I remove `-i ./hosts` then `packerHost` exists but `redis_host` is not defined. 

Is there a way to merge the two?
