### ISSUE TITLE
Bug using Docker builder and Ansible provisioner

### ISSUE THREAD

**Issue by Varkal** [mitchellh/packer#4716]
Hello

Seems Docker Builder and Ansible Provisioner doesn't work together:

```
packer build template.json

docker output will be in this color.

1 error(s) occurred:

* exit status 250
```

**Packer version** : Packer v0.12.3
**Host Platform** : Mac OSX 10.11.6
**Gist** : [https://gist.github.com/Varkal/648654989994588ff55008fb5c97195a](https://gist.github.com/Varkal/648654989994588ff55008fb5c97195a)

Doesn't found anything in documentation who discourage the use of those two together in the same build

**Comment by rickard-von-essen** [comment]
Most likely this is already working and just needs some documentation.

**Comment by rickard-von-essen** [comment]
Actually this works fine with some minor adjustments:

```json
{
  "builders" : [
    {
      "image" : "ubuntu:latest",
      "type" : "docker",
      "commit" : true
    }
  ],
  "provisioners" : [
    {
      "type": "shell",
      "inline": [ "apt-get update && apt-get install -y python" ]
    },
    {
      "playbook_file" : "playbook.yml",
      "type" : "ansible"
    }
  ]
}
```

```yaml
---
- hosts: all
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: install nginx
      apt:
        name: nginx
```

What's the output of:
```shell
docker info
ansible --version
```
